"""
Sector/Category definitions for Data Pack Platform
Matches Silver Oak DealCloud portal sectors
"""

SECTORS = [
    "Aesthetic Medical Services",
    "Anatomic Pathology",
    "Anesthesia Services",
    "Architectural Design",
    "Auction Services",
    "Auto Repair Services",
    "Automotive Care",
    "Behavioral Health Services",
    "BOD Family Entertainment Industry",
    "BPaaS (Business Process as a Service)",
    "Branded Products / Manufacturing",
    "Business Process Outsourcing",
    "Cancer Treatment Service Providers",
    "Chemical Distribution",
    "Chemical Manufacturing",
    "Claims Administration",
    "Cloud Hosting Services",
    "Colocation Managed Services",
    "Commercial Landscaping",
    "Commercial Security Services",
    "Communications Technology Distributors",
    "Consulting Services",
    "Consumer Financial Services",
    "Consumer Research & Insights",
    "Dental Implants",
    "Dermatology Pharmacy",
    "Diabetes DME",
    "Digital & IT Solutions Provider",
    "Education",
    "Electrical Components",
    "Energy Services",
    "Engineering Services",
    "Entertainment and Corporate Events",
    "Environmental Services",
    "ERP System Implementation",
    "Executive Coaching",
    "Experiential Travel Industry",
    "Extended Lifecycle IT",
    "Facilities Services",
    "Fertility Pharmacy Solution",
    "Financial Services",
    "Fitness",
    "Flower Distribution Industry",
    "Food and Beverage Chemicals",
    "Foodservice Distribution",
    "Freight Brokerage",
    "Hawaii Produce Industry",
    "Health & Wellness",
    "Healthcare Consulting",
    "Healthcare Facilities Services",
    "Industrial Services",
    "Integrated Marketing Agency",
    "IT Service Management",
    "IT Services",
    "Landscaping Services",
    "Laundry Services",
    "Lead Acid Battery Distributors",
    "Legal Services",
    "Location-Based Family Entertainment",
    "Long-Term Care Pharmacies",
    "Marketing Services",
    "Media Placement Partners",
    "Media Services",
    "Medical Products",
    "Medical Supplies Distribution",
    "Medspas",
    "Mental & Behavioral Health",
    "Outsourced Call Centers",
    "Outsourced Leave Management",
    "Outsourced Medical Transportation",
    "Outsourced Services to Payors",
    "Outsourced Services to Providers",
    "Performance Based Marketing",
    "Pet Care Services",
    "Pharmaceutical Services",
    "Pharmacy",
    "Point of Care Advertising",
    "Produce Distribution",
    "Promotional Products",
    "Provider Services",
    "QA Services",
    "Quality Assurance Services",
    "Residential Services",
    "Scaffolding Insulation",
    "Security Services",
    "Senior Living Facility Retailer",
    "SEO & Digital Marketing",
    "Software",
    "Solid Waste Collection and Disposal",
    "Transportation & Logistics",
    "Travel & Leisure",
    "Value Added Packaging",
    "Value-Added Distribution",
    "Vein Therapy",
    "Wellness Industry",
]

# Grouped by category for UI display
SECTOR_CATEGORIES = {
    "Healthcare": [
        "Aesthetic Medical Services",
        "Anatomic Pathology",
        "Anesthesia Services",
        "Behavioral Health Services",
        "Cancer Treatment Service Providers",
        "Dental Implants",
        "Dermatology Pharmacy",
        "Diabetes DME",
        "Fertility Pharmacy Solution",
        "Health & Wellness",
        "Healthcare Consulting",
        "Healthcare Facilities Services",
        "Long-Term Care Pharmacies",
        "Medical Products",
        "Medical Supplies Distribution",
        "Medspas",
        "Mental & Behavioral Health",
        "Outsourced Medical Transportation",
        "Outsourced Services to Payors",
        "Outsourced Services to Providers",
        "Pharmaceutical Services",
        "Pharmacy",
        "Point of Care Advertising",
        "Provider Services",
        "Vein Therapy",
        "Wellness Industry",
    ],
    "Business Services": [
        "BPaaS (Business Process as a Service)",
        "Business Process Outsourcing",
        "Claims Administration",
        "Consulting Services",
        "ERP System Implementation",
        "Executive Coaching",
        "Integrated Marketing Agency",
        "Legal Services",
        "Marketing Services",
        "Media Placement Partners",
        "Media Services",
        "Outsourced Call Centers",
        "Outsourced Leave Management",
        "Performance Based Marketing",
        "QA Services",
        "Quality Assurance Services",
        "SEO & Digital Marketing",
    ],
    "Technology": [
        "Cloud Hosting Services",
        "Colocation Managed Services",
        "Communications Technology Distributors",
        "Digital & IT Solutions Provider",
        "Extended Lifecycle IT",
        "IT Service Management",
        "IT Services",
        "Software",
    ],
    "Industrial & Manufacturing": [
        "Branded Products / Manufacturing",
        "Chemical Distribution",
        "Chemical Manufacturing",
        "Electrical Components",
        "Energy Services",
        "Engineering Services",
        "Environmental Services",
        "Industrial Services",
        "Lead Acid Battery Distributors",
        "Scaffolding Insulation",
        "Solid Waste Collection and Disposal",
    ],
    "Consumer & Retail": [
        "Auction Services",
        "Auto Repair Services",
        "Automotive Care",
        "Consumer Financial Services",
        "Consumer Research & Insights",
        "Fitness",
        "Flower Distribution Industry",
        "Pet Care Services",
        "Promotional Products",
        "Residential Services",
        "Senior Living Facility Retailer",
    ],
    "Food & Distribution": [
        "Food and Beverage Chemicals",
        "Foodservice Distribution",
        "Freight Brokerage",
        "Hawaii Produce Industry",
        "Produce Distribution",
        "Value Added Packaging",
        "Value-Added Distribution",
    ],
    "Facilities & Property": [
        "Architectural Design",
        "Commercial Landscaping",
        "Commercial Security Services",
        "Facilities Services",
        "Landscaping Services",
        "Laundry Services",
        "Security Services",
    ],
    "Entertainment & Travel": [
        "BOD Family Entertainment Industry",
        "Entertainment and Corporate Events",
        "Experiential Travel Industry",
        "Location-Based Family Entertainment",
        "Travel & Leisure",
    ],
    "Financial Services": [
        "Financial Services",
    ],
    "Education": [
        "Education",
    ],
}


def get_all_sectors():
    """Return flat list of all sectors"""
    return SECTORS.copy()


def get_sectors_by_category():
    """Return sectors grouped by category"""
    return SECTOR_CATEGORIES.copy()


def validate_sector(sector: str) -> bool:
    """Check if a sector is valid"""
    return sector in SECTORS
